[tool.poetry]
name = "yes"
version = "yes"
description = "yes"
authors = ["yes"]
license = "yes"

[tool.poetry.dependencies]
python = "yes"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
